[[bundles]]
name   = "files"
source = "local:/Users/mak/src/tabula-bundles/files"

[[bundles]]
name   = "drivers"
source = "local:/Users/mak/src/tabula-bundles/drivers"
skills = ["subagent-openai", "subagent-anthropic"]

[[bundles]]
name   = "memory"
source = "local:/Users/mak/src/tabula-bundles/memory"
